/**
 * 个股研报 — closed until you ask for it.
 *
 * Expanding fetches the half that already exists: fundamentals with growth,
 * revenue by product and by region, the latest forecast and express filings,
 * and the saved supply-chain graph. That is a few Tushare calls and arrives in
 * seconds.
 *
 * The four AI sections each cost a DeepSeek call, so each has its own 生成
 * button and each is cached forever afterwards. Nothing is generated by
 * opening the panel — asking for Porter's should not also bill PESTEL.
 *
 * 同业对比 is the section this is really for: the target and its peers on the
 * same rows, ranked within each column, so "cheapest", "highest margin" and
 * "fastest growing" read at a glance instead of by scanning numbers.
 */

import { useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";
import type { EquityBrief, Num, PeerRow, SegmentItem } from "../lib/types";
import { fixed, money, signed } from "../lib/format";
import { SupplyChainWindow } from "./SupplyChainWindow";

const AI_LABEL: Record<string, string> = {
  overview: "公司概览", porters: "波特五力", pestel: "PESTEL", competitors: "同业名单",
};

export function EquityBriefPanel({ ticker, market }: { ticker: string; market: string }) {
  const [open, setOpen] = useState(false);
  if (market !== "CN") return null;

  return (
    <section className="card">
      <button onClick={() => setOpen(!open)}
        className="w-full flex items-center gap-2 px-3 py-2.5 text-left hover:bg-elevated rounded-[10px]">
        <span className="text-[14px] font-semibold">📑 个股研报</span>
        <span className="label">
          基本面 · 收入构成 · 供应链 · 波特五力 · PESTEL · 同业对比
        </span>
        <span className="ml-auto text-ink-mute text-[13px]">{open ? "收起 ▲" : "展开生成 ▼"}</span>
      </button>
      {open && <Body ticker={ticker} />}
    </section>
  );
}

function Body({ ticker }: { ticker: string }) {
  const q = useQuery({
    queryKey: ["equity", ticker],
    queryFn: () => api.equity(ticker),
    staleTime: 20 * 60_000,
  });

  if (q.isPending) return <p className="label p-6 text-center">正在读取财务与构成数据…</p>;
  if (q.isError) {
    return (
      <p className="text-[12.5px] text-up p-6 text-center">
        {(q.error as Error).message}
        <button onClick={() => q.refetch()} className="ml-2 text-cyan">重试</button>
      </p>
    );
  }
  return <Report d={q.data!} />;
}

function Report({ d }: { d: EquityBrief }) {
  return (
    <div className="px-3 pb-3 flex flex-col gap-3 border-t border-line pt-3">
      <Peers d={d} />
      <div className="grid gap-3 xl:grid-cols-2 items-start">
        <Fundamentals d={d} />
        <div className="flex flex-col gap-3">
          <Segments d={d} />
          <Filings d={d} />
        </div>
      </div>
      <SupplyChain d={d} />
      <div className="grid gap-3 xl:grid-cols-2 items-start">
        <AiSection d={d} section="porters" />
        <AiSection d={d} section="pestel" />
      </div>
      <AiSection d={d} section="overview" />
      <p className="label leading-snug">
        财务数据来自 Tushare，同比增长采用其 or_yoy / netprofit_yoy —— A股中报为
        年内累计口径，直接用报表两期相减会拿半年比一个季度。AI 部分为模型生成，
        每个板块单独缓存，仅供参考。
      </p>
    </div>
  );
}

/** The section this panel exists for. */
function Peers({ d }: { d: EquityBrief }) {
  // Role comes from /me, not from the client session — the server is the
  // authority, and it re-checks on every admin write regardless of this.
  const me = useQuery({ queryKey: ["me"], queryFn: api.me, staleTime: 10 * 60_000 });
  const isAdmin = (me.data?.role ?? "").toLowerCase() === "admin";
  const [editing, setEditing] = useState(false);

  if (!d.peers) {
    return (
      <div className="rounded-lg bg-sunken px-3 py-3 flex items-center gap-3">
        <span className="text-[13px] font-semibold">🏁 同业对比</span>
        <span className="label">尚未生成同业名单</span>
        <GenerateButton ticker={d.ticker} section="competitors" />
      </div>
    );
  }

  const COLS: { k: keyof PeerRow; label: string; nd: number; suffix?: string; hint?: string }[] = [
    { k: "mv_yi", label: "市值", nd: 0 },
    { k: "pe_ttm", label: "PE(TTM)", nd: 1, hint: "低为佳；亏损股不参与排名" },
    { k: "pb", label: "PB", nd: 2, hint: "低为佳" },
    { k: "roe", label: "ROE", nd: 2, suffix: "%" },
    { k: "gross_margin", label: "毛利率", nd: 1, suffix: "%" },
    { k: "net_margin", label: "净利率", nd: 1, suffix: "%" },
    { k: "revenue_yoy", label: "营收YoY", nd: 1, suffix: "%" },
    { k: "profit_yoy", label: "利润YoY", nd: 1, suffix: "%" },
    { k: "debt_to_assets", label: "资产负债率", nd: 1, suffix: "%", hint: "低为佳" },
  ];

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-wrap items-baseline gap-x-3">
        <span className="text-[13px] font-semibold">🏁 同业对比</span>
        <span className="label">同期财报口径 · 每列第 1 名加粗，★ 为本股</span>
        {isAdmin && (
          <span className="ml-auto flex items-center gap-2">
            <button onClick={() => setEditing(!editing)} className="text-[12px] text-cyan">
              {editing ? "完成编辑" : "编辑同业名单"}
            </button>
            <SaveToSector d={d} />
          </span>
        )}
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-[12.5px] border-collapse">
          <thead>
            <tr className="text-ink-mute">
              <th className="text-left font-normal pb-1 pr-3">公司</th>
              {COLS.map((c) => (
                <th key={String(c.k)} title={c.hint}
                  className="text-right font-normal pb-1 px-2 whitespace-nowrap">{c.label}</th>
              ))}
              <th className="text-left font-normal pb-1 pl-2">为什么是同业</th>
            </tr>
          </thead>
          <tbody>
            {d.peers.rows.map((r) => (
              <tr key={r.ticker} className={`border-t border-line ${r.is_target ? "bg-sunken" : ""}`}>
                <td className="py-1 pr-3 whitespace-nowrap">
                  {r.is_target ? <span className="text-brand-ink">★ </span> : null}
                  <Link to={`/?t=${r.ticker}`} className="hover:text-cyan">
                    {r.name} <span className="font-mono tnum text-[11px] text-ink-mute">{r.ticker}</span>
                  </Link>
                </td>
                {COLS.map((c) => {
                  const v = r[c.k] as Num;
                  const best = r.ranks?.[String(c.k)] === 1;
                  return (
                    <td key={String(c.k)}
                      className={`py-1 px-2 text-right font-mono tnum whitespace-nowrap ${
                        best ? "font-semibold text-up" : "text-ink-dim"}`}>
                      {v == null ? "—"
                        : c.k === "mv_yi" ? money((v as number) * 1e8, "CNY")
                          : `${fixed(v, c.nd)}${c.suffix ?? ""}`}
                    </td>
                  );
                })}
                <td className="py-1 pl-2 text-ink-mute truncate max-w-[26ch]" title={r.why}>{r.why}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {editing && isAdmin && <PeerEditor d={d} onDone={() => setEditing(false)} />}
    </div>
  );
}

function PeerEditor({ d, onDone }: { d: EquityBrief; onDone: () => void }) {
  const qc = useQueryClient();
  const current = (d.ai.competitors?.competitors ?? []).map((c) => `${c.ticker} ${c.name}`).join("\n");
  const [text, setText] = useState(current);

  const save = useMutation({
    mutationFn: () => {
      const rows = text.split("\n").map((line) => {
        const m = line.trim().match(/^(\d{6})\s*(.*)$/);
        return m ? { ticker: m[1]!, name: (m[2] || "").trim(), why: "" } : null;
      }).filter((x): x is { ticker: string; name: string; why: string } => x !== null);
      return api.equitySavePeers(d.ticker, rows);
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["equity", d.ticker] });
      onDone();
    },
  });

  return (
    <div className="rounded-lg bg-sunken p-2.5 flex flex-col gap-2">
      <span className="label">
        每行一只：六位代码 + 名称。保存会覆盖该股的同业名单（管理员操作，对所有用户生效）。
      </span>
      <textarea value={text} onChange={(e) => setText(e.target.value)} rows={6}
        className="bg-panel rounded-md p-2 text-[12.5px] font-mono tnum outline-none focus:ring-2 focus:ring-cyan/40" />
      <div className="flex items-center gap-2">
        <button onClick={() => save.mutate()} disabled={save.isPending}
          className="h-7 px-3 rounded-md bg-cyan text-white text-[12.5px] font-semibold disabled:opacity-60">
          {save.isPending ? "保存中…" : "保存名单"}
        </button>
        <button onClick={onDone} className="text-[12px] text-ink-mute">取消</button>
        <GenerateButton ticker={d.ticker} section="competitors" force label="用AI重新生成" />
        {save.isError && <span className="text-[12px] text-up">{(save.error as Error).message}</span>}
      </div>
    </div>
  );
}

function SaveToSector({ d }: { d: EquityBrief }) {
  const [open, setOpen] = useState(false);
  const [sector, setSector] = useState("");
  const names = useQuery({ queryKey: ["sector-names"], queryFn: api.sectorNames, enabled: open });

  const save = useMutation({
    mutationFn: () => api.equitySaveSector(
      d.ticker, sector.trim(),
      [d.ticker, ...(d.peers?.rows.filter((r) => !r.is_target).map((r) => r.ticker) ?? [])]),
  });

  if (!open) {
    return <button onClick={() => setOpen(true)} className="text-[12px] text-cyan">保存为板块</button>;
  }
  return (
    <span className="flex items-center gap-1.5">
      <input list="sector-names" value={sector} onChange={(e) => setSector(e.target.value)}
        placeholder="板块名称（可新建）"
        className="h-7 w-40 px-2 rounded-md bg-sunken text-[12.5px] outline-none focus:ring-2 focus:ring-cyan/40" />
      <datalist id="sector-names">
        {(names.data ?? []).map((n) => <option key={n} value={n} />)}
      </datalist>
      <button onClick={() => save.mutate()} disabled={!sector.trim() || save.isPending}
        className="h-7 px-2 rounded-md bg-cyan text-white text-[12px] disabled:opacity-60">
        {save.isPending ? "…" : "保存"}
      </button>
      <button onClick={() => setOpen(false)} className="text-[12px] text-ink-mute">取消</button>
      {save.isSuccess && (
        <span className="text-[12px] text-up">
          已加入 {save.data.sector}（{save.data.added} 只{save.data.created ? "，新建板块" : ""}）
        </span>
      )}
      {save.isError && <span className="text-[12px] text-up">{(save.error as Error).message}</span>}
    </span>
  );
}

function Fundamentals({ d }: { d: EquityBrief }) {
  const rows = d.fundamentals.periods;
  if (rows.length === 0) return <p className="label">暂无财务数据。</p>;
  return (
    <div className="min-w-0">
      <div className="text-[13px] font-semibold mb-1">📊 基本面与同比</div>
      <div className="overflow-x-auto">
        <table className="w-full text-[12px] border-collapse">
          <thead>
            <tr className="text-ink-mute">
              <th className="text-left font-normal pb-1 pr-2">报告期</th>
              <th className="text-right font-normal pb-1 px-2">营收</th>
              <th className="text-right font-normal pb-1 px-2">同比</th>
              <th className="text-right font-normal pb-1 px-2">归母净利</th>
              <th className="text-right font-normal pb-1 px-2">同比</th>
              <th className="text-right font-normal pb-1 px-2">毛利率</th>
              <th className="text-right font-normal pb-1 px-2">净利率</th>
              <th className="text-right font-normal pb-1 pl-2">ROE</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((p) => (
              <tr key={p.period} className="border-t border-line">
                <td className="py-1 pr-2 font-mono tnum">{p.period}</td>
                <td className="py-1 px-2 text-right font-mono tnum">{money(p.revenue, "CNY")}</td>
                <td className={`py-1 px-2 text-right font-mono tnum ${
                  (p.revenue_yoy ?? 0) > 0 ? "text-up" : (p.revenue_yoy ?? 0) < 0 ? "text-down" : ""}`}>
                  {signed(p.revenue_yoy, 1, "%")}
                </td>
                <td className="py-1 px-2 text-right font-mono tnum">{money(p.net_profit, "CNY")}</td>
                <td className={`py-1 px-2 text-right font-mono tnum ${
                  (p.profit_yoy ?? 0) > 0 ? "text-up" : (p.profit_yoy ?? 0) < 0 ? "text-down" : ""}`}>
                  {signed(p.profit_yoy, 1, "%")}
                </td>
                <td className="py-1 px-2 text-right font-mono tnum text-ink-dim">{fixed(p.gross_margin, 1)}%</td>
                <td className="py-1 px-2 text-right font-mono tnum text-ink-dim">{fixed(p.net_margin, 1)}%</td>
                <td className="py-1 pl-2 text-right font-mono tnum text-ink-dim">{fixed(p.roe, 2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

const SEG_COLORS = ["#0062cc", "#7c3aed", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#64748b"];

function Segments({ d }: { d: EquityBrief }) {
  return (
    <div className="flex flex-col gap-2">
      <div className="text-[13px] font-semibold">🧩 收入构成</div>
      {(["product", "region"] as const).map((kind) => {
        const s = d.segments[kind];
        const label = kind === "product" ? "按产品" : "按地区";
        if (!s.items.length) {
          return <p key={kind} className="label">{label}：公司未披露此口径。</p>;
        }
        return (
          <div key={kind} className="flex flex-col gap-1">
            <div className="flex items-baseline gap-2">
              <span className="text-[12.5px]">{label}</span>
              <span className="label">{s.period}</span>
            </div>
            <div className="flex h-4 rounded-sm overflow-hidden bg-sunken">
              {s.items.map((it, i) => (
                <span key={it.item} title={`${it.item} ${it.share_pct}%`}
                  style={{ width: `${it.share_pct ?? 0}%`, background: SEG_COLORS[i % SEG_COLORS.length] }} />
              ))}
            </div>
            <div className="flex flex-wrap gap-x-3 gap-y-0.5">
              {s.items.map((it, i) => <SegLegend key={it.item} it={it} color={SEG_COLORS[i % SEG_COLORS.length]!} />)}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function SegLegend({ it, color }: { it: SegmentItem; color: string }) {
  return (
    <span className="text-[11.5px] flex items-center gap-1"
      title={it.margin_pct != null ? `分部毛利率 ${it.margin_pct}%` : undefined}>
      <i className="inline-block w-2 h-2 rounded-sm" style={{ background: color }} />
      {it.item} <span className="font-mono tnum text-ink-mute">{fixed(it.share_pct, 1)}%</span>
    </span>
  );
}

function Filings({ d }: { d: EquityBrief }) {
  const { forecast, express } = d.filings;
  if (!forecast.length && !express.length) {
    return <p className="label">暂无业绩预告或快报。</p>;
  }
  return (
    <div className="flex flex-col gap-1">
      <div className="text-[13px] font-semibold">📄 最新业绩预告 / 快报</div>
      {forecast.slice(0, 3).map((f, i) => (
        <div key={`f${i}`} className="rounded-lg bg-sunken px-2.5 py-1.5 text-[12px]">
          <div className="flex items-baseline gap-2">
            <b>{String(f.type ?? "预告")}</b>
            <span className="font-mono tnum">{String(f.end_date ?? "")}</span>
            <span className="text-ink-mute ml-auto">公告 {String(f.ann_date ?? "")}</span>
          </div>
          <div className="text-ink-dim">
            净利变动 {signed(f.p_change_min as number, 1, "%")} ~ {signed(f.p_change_max as number, 1, "%")}
          </div>
          {f.change_reason && (
            <p className="text-ink-mute leading-snug mt-0.5">{String(f.change_reason).slice(0, 160)}</p>
          )}
        </div>
      ))}
      {express.slice(0, 2).map((e, i) => (
        <div key={`e${i}`} className="rounded-lg bg-sunken px-2.5 py-1.5 text-[12px]">
          <div className="flex items-baseline gap-2">
            <b>快报</b><span className="font-mono tnum">{String(e.end_date ?? "")}</span>
          </div>
          <div className="text-ink-dim">
            营收 {money(e.revenue as number, "CNY")} · 净利 {money(e.n_income as number, "CNY")}
            {e.yoy_net_profit != null && ` · 同比 ${signed(e.yoy_net_profit as number, 1, "%")}`}
          </div>
        </div>
      ))}
    </div>
  );
}

function SupplyChain({ d }: { d: EquityBrief }) {
  const [open, setOpen] = useState(false);
  const g = d.supply_chain;
  const products = g?.products ?? [];
  const sectors = g?.macro_sectors ?? [];

  if (!products.length) {
    return (
      <div className="flex items-center gap-3">
        <span className="text-[13px] font-semibold">🔗 供应链</span>
        <span className="label">尚未生成</span>
        <GenerateButton ticker={d.ticker} section="supply-chain" label="生成供应链图" />
      </div>
    );
  }

  return (
    <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
      <span className="text-[13px] font-semibold">🔗 供应链</span>
      <span className="label">
        {products.length} 个产品 → {sectors.length} 个下游行业 · {g?.links?.length ?? 0} 条供货关系
      </span>
      <span className="flex flex-wrap gap-1">
        {products.slice(0, 4).map((p) => (
          <span key={p} className="rounded-md bg-sunken px-1.5 py-0.5 text-[11.5px]">
            {p.split(" / ")[1] || p}
          </span>
        ))}
        {products.length > 4 && <span className="label">+{products.length - 4}</span>}
      </span>
      <button onClick={() => setOpen(true)}
        className="ml-auto h-7 px-2.5 rounded-md border border-cyan text-cyan text-[12.5px]">
        打开供应链图 ↗
      </button>
      {open && g && (
        <SupplyChainWindow ticker={d.ticker} graph={g} onClose={() => setOpen(false)} />
      )}
    </div>
  );
}


function GenerateButton({ ticker, section, force = false, label }: {
  ticker: string; section: string; force?: boolean; label?: string;
}) {
  const qc = useQueryClient();
  const run = useMutation({
    mutationFn: () => api.equityGenerate(ticker, section, force),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["equity", ticker] }),
  });
  return (
    <span className="flex items-center gap-2">
      <button onClick={() => run.mutate()} disabled={run.isPending}
        className="h-7 px-2.5 rounded-md bg-violet text-white text-[12px] font-semibold disabled:opacity-60">
        {run.isPending ? "生成中…（20–60秒）" : label ?? `生成${AI_LABEL[section] ?? section}`}
      </button>
      {run.isError && <span className="text-[12px] text-up">{(run.error as Error).message}</span>}
    </span>
  );
}

/** Renders whatever shape the model returned, without assuming one. */
function AiSection({ d, section }: { d: EquityBrief; section: "overview" | "porters" | "pestel" }) {
  const payload = d.ai[section];
  return (
    <div className="flex flex-col gap-1.5">
      <div className="flex items-baseline gap-2">
        <span className="text-[13px] font-semibold">
          {section === "porters" ? "⚔️ 波特五力" : section === "pestel" ? "🌐 PESTEL" : "🏢 公司概览"}
        </span>
        {d.generated_at[section] && (
          <span className="label">生成于 {String(d.generated_at[section]).slice(0, 10)}</span>
        )}
        <span className="ml-auto">
          {payload
            ? <GenerateButton ticker={d.ticker} section={section} force label="重新生成" />
            : <GenerateButton ticker={d.ticker} section={section} />}
        </span>
      </div>
      {!payload && <p className="label">尚未生成。</p>}
      {payload && <Tree value={payload} />}
    </div>
  );
}

function Tree({ value, depth = 0 }: { value: unknown; depth?: number }) {
  if (value == null) return null;
  if (typeof value === "string" || typeof value === "number") {
    return <p className="text-[12.5px] text-ink-dim leading-snug">{String(value)}</p>;
  }
  if (Array.isArray(value)) {
    return (
      <ul className="flex flex-col gap-0.5 list-disc pl-4">
        {value.map((v, i) => <li key={i} className="text-[12.5px]"><Tree value={v} depth={depth + 1} /></li>)}
      </ul>
    );
  }
  if (typeof value === "object") {
    return (
      <div className={`flex flex-col gap-1.5 ${depth > 0 ? "pl-1" : ""}`}>
        {Object.entries(value as Record<string, unknown>).map(([k, v]) => (
          <div key={k}>
            <div className="text-[12px] font-medium">{k}</div>
            <Tree value={v} depth={depth + 1} />
          </div>
        ))}
      </div>
    );
  }
  return null;
}
